services:
  warehouse:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgressql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d source"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - docker-network
  
  warehouseui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./db-ui-data:/var/lib/pgadmin
    ports:
      - "8085:80"
    networks:
      - docker-network
  
  orchestrator:
    image: mageai/mageai:latest
    volumes:
      - ./orchestrator-data:/home/src
    ports:
      - "6789:6789"
    command: /app/run_app.sh mage start scheduler
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

  
